version: '3.9' services:
  elasticsearch:
    image: elasticsearch:7.17.9
    hostname: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - dbase-network
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: kibana:7.17.9
    hostname: kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - dbase-network volumes:
  elasticsearch-data:
    driver: local
  db_booking: networks:
  dbase-network:
